### ISSUE TITLE
BUG: tags don't display well in on certain other users profile

### ISSUE THREAD

**Issue by louiscrc** [Swent-team-6/icebreakrr#106]
When I display different users' profiles on the **Around You** page, some profiles display correctly (like *Valentin's*), but others have their tags cropped (such as *Ratz's*).

This happens on a Pixel Pro 8 emulator.

<img width="171" alt="image" src="https://github.com/user-attachments/assets/f3900b27-d4c6-4322-bc4b-653dac8744a0"> <img width="171" alt="image" src="https://github.com/user-attachments/assets/3164b9a2-3a95-4866-878e-0a495e28d807">

**Comment by MaxCastelCast** [comment]
Yes this is resolved now !
