### ISSUE TITLE
BUG: tagselector from profile creation has extreme text size

### ISSUE THREAD

**Issue by Kapestian** [Swent-team-6/icebreakrr#135]
![image](https://github.com/user-attachments/assets/59fdb294-b667-4e07-a95f-14c3e22879a7)
### I think the issue might be the due to missuese of constants here:
![image](https://github.com/user-attachments/assets/79ec1c4c-6582-4367-a252-ca1fd0ee9a2d)

**Comment by MaxCastelCast** [comment]
Yes indeed ! The textSize was wayyyyy to big and the onStringChanged was incomplete
