### ISSUE TITLE
BUG: Weird text display when sending request

### ISSUE THREAD

**Issue by Kapestian** [Swent-team-6/icebreakrr#219]
the text is a bit hidden :
![image](https://github.com/user-attachments/assets/e95a5e5c-5401-43b9-b4da-4471a4b3d8e1)

In addition to that, the behavior on text overflow consist of "swapping" the content of text already written with new text, which is confusing and also make edition complicated:
![studio64_ZVIivL70fJ](https://github.com/user-attachments/assets/ec420704-9d0d-452a-b038-d76ee4311371)

tasks:
- [ ] fix hidden text
- [ ] make text overflow more user-friendly

**Comment by louiscrc** [comment]
New version improved !
![Image](https://github.com/user-attachments/assets/9cc5b58e-46bd-438c-bd37-7e6f4f2325f6)
