### ISSUE TITLE
invalid: maps screen recomputes some values

### ISSUE THREAD

**Issue by Kapestian** [Swent-team-6/icebreakrr#267]
`markerStates` and `userMarkers` seem to be recomputed at every screen recomposition. It may lead to performance issues and should be fixed.

**Comment by MaxCastelCast** [comment]
You are talking about which screen ? The MapView one ?

**Comment by MaxCastelCast** [comment]
Well, it is necessary to recompute the markerStates and UserMarkers each time the camera is moving to addapt it to the translation of the map, so the implementation of the map is legit
