### ISSUE TITLE
BUG: security vulnerability when selectedProfile is (briefly) another user's profile when reaching settings screen

### ISSUE THREAD

**Issue by Kapestian** [Swent-team-6/icebreakrr#63]
If we look at the page of another user, the value of `selectedProfile` is set to this user, and if we go to the settings profile, there is a brief moment where `selectedProfile` user switches from the other profiles to ours, and thus a very, very small moment where you could technically change another user's profile if you are faster than the network (possible in Uganda).

Here are some ideas to fix the issue:
- add a loading page to the settings screen until our profile is loaded (Best option so we can remove loading from editProfile screen and thus avoid visual issues when changing profile picture)
- Make `selectedProfile` null every time we navigate back to overviewScreen
- put assertions that the uid of `selectedProfile` is the same of `auth.currentUser` (I think we should do this anyway)

**Comment by MaxCastelCast** [comment]
Yes this is a first priority problem
