### ISSUE TITLE
BUG : autorefresh from editProfile to AroundYou

### ISSUE THREAD

**Issue by SamSteu** [Swent-team-6/icebreakrr#71]
When you edit your profile and go to the around you your profile isn't automatically refreshed. When you refresh the page you can indeed see your updated profile : 

https://github.com/user-attachments/assets/2209a4e7-3677-4019-b2f1-d0f85688a811

**Comment by BotondAKovacs** [comment]
Isn't the problem rather that you can see yourself?

**Comment by SamSteu** [comment]
Thanks for asking! The fact that we can see each other is an issue that we need to fix. But this shows us that the `aroundYou` isn't automatically refreshed when we arrive on the screen, which is not supposed to happen.

**Comment by BotondAKovacs** [comment]
I believe Arthur is working on refreshing the list of profiles every few seconds regardless of where you are in the app, would that be enough?

**Comment by SamSteu** [comment]
Yes that would be enough, he can link this issue with his PR I guess.

**Comment by Kapestian** [comment]
@louiscrc is also working on changing `selectedProfile` with `selfProfile` in these screens. This may cause more problems if you try to fix in between. Please try to solve that on discord
