### ISSUE TITLE
INVALID: increase the height of a tag in DisplayProfile

### ISSUE THREAD

**Issue by SamSteu** [Swent-team-6/icebreakrr#73]
When you click on a profile that has only one row of tags, the height of the TagSelector is too small to show entirely the tag. You need to modify the `tagHeight` variable in `DisplayProfile` : 

https://github.com/user-attachments/assets/f93aa826-1484-4ca1-8b70-7bab7c3838da

**Comment by MaxCastelCast** [comment]
Ok i take care of that
