### ISSUE TITLE
INVALID: takes too much time to tell us that we have no more connection

### ISSUE THREAD

**Issue by SamSteu** [Swent-team-6/icebreakrr#75]
https://github.com/user-attachments/assets/f0011b17-5422-4f22-8d11-749423871d24

**Comment by BotondAKovacs** [comment]
We did that to avoid the app becoming unusable for small interuptions in connectivity, it's programmed to wait 15 seconds right nowm but we can discuss a change.

**Comment by SamSteu** [comment]
Okay thanks for the clarifications, I believe we can talk about it because 15 seconds feels long.
